export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_ITEM_QUANTITY_STEP = "CART_ITEM_QUANTITY_STEP";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_CLEAR = "CART_CLEAR";
export const CART_TOTALS_UPDATE = "CART_TOTALS_UPDATE";
