export const PRODUCT_LIST_LOAD = "PRODUCT_LIST_LOAD";
export const PRODUCT_LIST_SORT = "PRODUCT_LIST_SORT";
export const PRODUCT_LIST_FILTER = "PRODUCT_LIST_FILTER";

export const PRODUCT_SORT_TYPE_UPDATE = "PRODUCT_SORT_TYPE_UPDATE";
export const PRODUCT_FILTERS_UPDATE = "PRODUCT_FILTERS_UPDATE";
export const PRODUCT_FILTERS_CLEAR = "PRODUCT_FILTERS_CLEAR";
