export const PRODUCTS_LOAD = "PRODUCTS_LOAD";
export const PRODUCTS_SORT = "PRODUCTS_SORT";
export const PRODUCTS_FILTER = "PRODUCTS_FILTER";

export const PRODUCT_SORT_TYPE_UPDATE = "PRODUCT_SORT_TYPE_UPDATE";
export const PRODUCT_FILTERS_UPDATE = "PRODUCT_FILTERS_UPDATE";
export const PRODUCT_FILTERS_CLEAR = "PRODUCT_FILTERS_CLEAR";
