export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";

export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_ERROR = "USER_LOGOUT_ERROR";

export const USER_GET_CURRENT = "USER_GET_CURRENT";
export const USER_GET_CURRENT_SUCCESS = "USER_GET_CURRENT_SUCCESS";
export const USER_GET_CURRENT_ERROR = "USER_GET_CURRENT_ERROR";

export const POST_LOGIN_PATH_UPDATE = "POST_LOGIN_PATH_UPDATE";
