export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";

export const PRODUCT_LIST_GRID_VIEW = "PRODUCT_LIST_GRID_VIEW";
export const PRODUCT_LIST_LIST_VIEW = "PRODUCT_LIST_LIST_VIEW";
